apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
    - name: build-image
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
        kind: ClusterTask
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: "--count --max-complexity=10 --max-line-length=127 --statistics"
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      runAfter:
        - lint
      taskRef:
        name: nose
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      runAfter:
        - tests
        - lint
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.build-image)"
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            echo "Updating manifest..."
            sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
            cat deploy/deployment.yaml
            echo "Deploying to OpenShift..."
            oc apply -f deploy/
            oc get pods -l app=accounts
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
